# _config.yml

description: "Exploring the MNIST dataset using t-SNE"
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    delimiters:
      inline: ['$', '$']    # Delimiters for inline math
      block: ['$$', '$$']    # Delimiters for block math

plugins:
  - jekyll-mathjax

# Optional: Specify the base URL if your site is hosted in a subdirectory
# baseurl: "/your-repo-name"

# Optional: Set the URL to your GitHub Pages site
# url: "https://yourusername.github.io"

# Exclude unnecessary files from the build
exclude:
  - "*.Rhistory"
  - "*.Rapp.history"
  - "*.RData"
  - "*.tar.gz"
  - "*.Rcheck/"
  - ".gitignore"
  - ".gitattributes"
  - "cache/"
  - "vignettes/*.html"
  - "vignettes/*.pdf"

# Include specific directories
include:
  - _pages
  - _posts
  - _layouts
  - images
  - Dimension_reduction_files/figure-gfm
